### ISSUE TITLE
The continuous benchmarking links seem broken

### ISSUE THREAD

**Issue by filmil** [unicode-org/icu4x#279] opened 2020-09-29 01:20 UTC
For example:
https://unicode-org.github.io/icu4x-docs/dev/locale/bench is a 404

@echeran Is this supposed to work at the moment?

**Comment by filmil** [comment] 2020-09-29 01:20
Related to https://github.com/unicode-org/icu4x/pull/197

**Comment by sffc** [comment] 2020-10-01 18:28
Dupe of #262?

**Comment by sffc** [comment] 2020-10-03 05:06
Also broken: https://unicode-org.github.io/icu4x-docs/icu_locale/index.html

**Comment by echeran** [comment] 2020-10-12 18:12
Yes, this is a duplicate of #262, which is now fixed, so I will close this issue now, accordingly.  The link above that was broken is now changed to be https://unicode-org.github.io/icu4x-docs/doc/icu_locale/index.html.  The link on the main Readme.md to the API docs works now.

**Closed by echeran** 2020-10-12 18:12 UTC
Labels: C-process, T-bug
