### ISSUE TITLE
Implement a conversion from `f64` to `FixedDecimal`

### ISSUE THREAD

**Issue by filmil** [unicode-org/icu4x#340] opened 2020-10-13 17:13 UTC
This is in addition to other conversions that `FixedDecimal` already has.

The conversion from `f64` needs to be slightly more complex, probably also requiring providing the formatting options separately.

**Comment by sffc** [comment] 2020-10-14 01:44
I'm going to mark this as a duplicate of https://github.com/unicode-org/icu4x/issues/166.

**Closed by sffc** 2020-10-14 01:44 UTC
