### ISSUE TITLE
C++/Rust FFI

### ISSUE THREAD

**Issue by nciric** [unicode-org/icu4x#46] opened 2020-04-18 22:47 UTC
One of the questions we had from clients was how hard is it to use library through FFI.

I played around with C++, Rust & cbindgen, based on [Rust FFI Omnibus](http://jakegoulding.com/rust-ffi-omnibus/) and other sites.

Here are results in my [experimental repo](https://github.com/nciric/experimental/tree/master/ffi) - files of interest are main.cc, lib.rs.

I could document findings so far if people feel it's useful. We can expand it over time.

**Comment by hsivonen** [comment] 2020-04-20 06:49
For C++ API ergonomics a [writeup about how encoding_rs available to Gecko](https://hsivonen.fi/modern-cpp-in-rust/) and the [related talk](https://media.ccc.de/v/rustfest18-5-a_rust_crate_that_also_quacks_like_a_modern_c_library), might be of interest. These were a manual effort rather than cbindgen. I haven't checked how closely cbindgen can automate this these days.

**Comment by sffc** [comment] 2020-04-30 18:25
@hagbard has some thoughts on this as well.

**Comment by zbraniecki** [comment] 2020-04-30 18:25
Additional backpointers:

- https://crisal.io/words/2020/02/28/C++-rust-ffi-patterns-1-complex-data-structures.html
- https://gist.github.com/zbraniecki/b251714d77ffebbc73c03447f2b2c69f

**Comment by sffc** [comment] 2021-03-12 18:10
Dupe of #398

**Closed by sffc** 2021-03-12 18:10 UTC
Labels: A-design, A-ffi, C-meta, T-docs
