### ISSUE TITLE
Require an example on how to use the BufferProvider to obtain the CodePointSetData result object.

### ISSUE THREAD

**Issue by rizzen-yazston** [unicode-org/icu4x#2808] opened 2022-11-04 08:11 UTC
Failing to understand how to use `BufferProvider` (also `FsDataProvider`) using Bincode1 format to obtain the resultant `CodePointSetData` for a specific key `DataKey` such as `Pat_Syn@1`. In order to use methods of `CodePointSetData` such as `as_borrowed().contains( char )`.

Considering the `icu_properties` crate does not have buffer methods in order to use `BufferProvider` structs, thus need to manually obtain the `CodePointSetData`.

The provided examples of the various mods seems to focus on a single aspect particular to a struct or module, and not how to integrate the various components of ICU4X together to get the desired usage of the ICU4X library.

**Comment by sffc** [comment] 2022-11-04 17:30
> Considering the icu_properties crate does not have buffer methods in order to use BufferProvider structs, thus need to manually obtain the CodePointSetData.

Good catch. You should do

```rust
icu_properties::sets::load_pattern_white_space(buffer_provider.as_deserializing())
```

This should be documented.

**Comment by rizzen-yazston** [comment] 2022-11-05 14:57
I tried your suggestion, yet obtaining a trait bound error for this snippet:

```
use icu_provider::prelude::*;
use icu_provider::serde::AsDeserializingBufferProvider;
use icu_properties::sets::{load_pattern_white_space, load_pattern_syntax, CodePointSetData};

pub fn try_new( buffer_provider: Box<dyn BufferProvider> ) -> Result<Self, String> {
    let syntax = match load_pattern_syntax(
        &buffer_provider.as_deserializing()
    ) {
        Err( _ ) => return Err( "Failed to load Pattern_Syntax.".to_string() ),
        Ok( response ) => response
    };

    /* -- snip remainder of the logic -- */
}
```
There error:
```
error[E0277]: the trait bound `for<'de> PropertyCodePointSetV1<'de>: serde::de::Deserialize<'_>` is not satisfied
    --> ????.rs:119:13
     |
118  |         let syntax = match load_pattern_syntax(
     |                                 ------------------- required by a bound introduced by this call
119  |             &buffer_provider.as_deserializing()
     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `for<'de> serde::de::Deserialize<'_>` is not implemented for `PropertyCodePointSetV1<'de>`
     |
     = help: the following other types implement trait `serde::de::Deserialize<'de>`:
               &'a Path
               &'a [u8]
               &'a str
               ()
               (T0, T1)
               (T0, T1, T2)
               (T0, T1, T2, T3)
               (T0, T1, T2, T3, T4)
             and 130 others
     = note: required because of the requirements on the impl of `for<'de> serde::de::Deserialize<'de>` for `YokeTraitHack<PropertyCodePointSetV1<'de>>`
     = note: required because of the requirements on the impl of `DataProvider<PatternSyntaxV1Marker>` for `DeserializingBufferProvider<'_, Box<dyn icu_provider::BufferProvider>>`
note: required by a bound in `load_pattern_syntax`
    --> /home/?????/.cargo/registry/src/github.com-1ecc6299db9ec823/icu_properties-1.0.0/src/sets.rs:1211:1
     |
1211 | / make_set_property! {
1212 | |     property: "Pattern_Syntax";
1213 | |     marker: PatternSyntaxProperty;
1214 | |     keyed_data_marker: PatternSyntaxV1Marker;
...    |
1235 | |     pub fn load_pattern_syntax();
1236 | | }
     | |_^ required by this bound in `load_pattern_syntax`
     = note: this error originates in the macro `make_set_property` (in Nightly builds, run with -Z macro-backtrace for more info)

```

**Comment by sffc** [comment] 2022-11-05 18:03
Please enable the icu_properties/serde feature.

**Comment by rizzen-yazston** [comment] 2022-11-05 18:57
Thanks. My code compiled without error.

Apologise for all these queries, I still getting the hang of using the new API.

My next attempt is add `icu_segmenter`. Hopefully I will enabled all the experimental features for various icu crates. I like to provide an example using providers implementing `BufferProvider` with `icu_properties` and `icu_segmenter`. The provider for example will be from `'icu_testdata`.

**Comment by rizzen-yazston** [comment] 2022-11-06 07:25
Here is a working example below the line

-----------------------------------------------------------------
In order for the example to function the following features are required in the `Cargo.toml` file, as `BufferProvider` data needs to be deserialised.

Currently for `icu_testdata`, the segmenter data is still experimental, and needs to be enabled.

```
[dependencies.icu_provider]
version = "1.0.0"
# Needed for BufferProvider
features = [ "serde", "deserialize_bincode_1" ]

[dependencies.icu_properties]
version = "1.0.0"
# Needed for BufferProvider
features = [ "serde" ]

[dependencies.icu_segmenter]
version = "0.7.0"
# Needed for BufferProvider
features = [ "serde" ]

[dependencies.icu_testdata]
version = "1.0.0"
# Needed for BufferProvider and icu_segmenter
features = [ "buffer", "icu_segmenter" ]
```

Example is a typical use case when requiring data from multiple data keys:

```
use icu_provider::prelude::*;
use icu_provider::serde::AsDeserializingBufferProvider;
use icu_properties::sets::{load_pattern_white_space, load_pattern_syntax, CodePointSetData};
use icu_segmenter::GraphemeClusterBreakSegmenter;
use icu_testdata::buffer;

pub fn get_data( buffer_provider: Box<dyn BufferProvider> )
    -> Result<(CodePointSetData, GraphemeClusterBreakSegmenter), String> {
    let syntax = match load_pattern_syntax(
        &buffer_provider.as_deserializing()
    ) {
        Err( _ ) => return Err( "Failed to load Pattern_Syntax.".to_string() ),
        Ok( response ) => response
    };
    let grapheme_segmenter = match GraphemeClusterBreakSegmenter::try_new_unstable(
        &buffer_provider.as_deserializing()
    ) {
        Err(_) => return Err( "Failed to get grapheme segmenter.".to_string() ),
        Ok( segmenter ) => segmenter
    };
    Ok( (syntax, grapheme_segmenter) )
}

let buffer_provider = Box::new( buffer() );
let ( syntax, segmenter ) = match get_data( buffer_provider ) {
    Err( error ) => println!( "{}", error ),
    Ok( result ) => result
};
asset!( syntax.contains( '\u{201c}' ) );
let breakpoints: Vec<usize> = segmenter.segment_str("Hello \u{1f5fa}").collect();
// World Map (U+1F5FA) is encoded in four bytes in UTF-8.
assert_eq!(&breakpoints, &[0, 1, 2, 3, 4, 5, 6, 10]);

```

**Comment by sffc** [comment] 2022-12-22 17:36
Marking as a duplicate of #2853 to consolidate our efforts to improve docs around features.

**Closed by sffc** 2022-12-22 17:36 UTC
Labels: T-docs-tests, C-unicode, S-tiny
