### ISSUE TITLE
Move all benchmark GitHub pages into common `/benchmarks` folder

### ISSUE THREAD

**Issue by gregtatum** [unicode-org/icu4x#471] opened 2021-02-01 23:00 UTC
This is a follow-up to #107. Currently the perf benchmarks are still output to the base directory, but should be uploaded instead to `/benchmarks/perf/*`.

**Comment by sffc** [comment] 2021-02-12 18:50
Dupe of #483

**Closed by sffc** 2021-02-12 18:50 UTC
