### ISSUE TITLE
Programmatically check that Serde borrows everywhere it is required

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#935] opened 2021-08-05 07:03 UTC
Follow-up from https://github.com/unicode-org/icu4x/pull/930

We should make `#[icu_provider::data_struct]` verify that data structs have `#[serde(borrow)]` everywhere that annotation is needed.

**Comment by sffc** [comment] 2022-02-09 00:19
We should prioritize this.

**Comment by sffc** [comment] 2022-02-09 17:47
A few options:

- Runtime test by instrumenting the global allocator
- Clippy lint? Might not be perfect.

**Comment by robertbastian** [comment] 2022-03-09 16:24
Duplicate of #1661

**Closed by robertbastian** 2022-03-09 16:24 UTC
Labels: C-data-infra, v1, T-techdebt, S-small
