### ISSUE TITLE
Short-term fix to make coverage CI check pass

### ISSUE THREAD

**Issue by echeran** [unicode-org/icu4x#316] opened 2020-10-09 17:43 UTC
In order to immediately unblock coverage checks, we should remove caching from the coverage checks in CI.  (ex: #312)

The longer-term solution is represented separately in #315.

**Comment by zbraniecki** [comment] 2020-10-13 17:05
that has been merged now.

**Comment by echeran** [comment] 2020-10-13 17:36
The PR to remove caching from the CI coverage checks has been merged.  Even though we thought that it would fix the immediate problem, we're currently not seeing the CI coverage checks pass.  I want to keep this issue open until we get that working.

**Comment by echeran** [comment] 2020-10-13 18:49
There is nothing official.  And there wasn't anything open-source worth trying, at least when I started GH Actions stuff in the summer..  It looks like, in that relatively short time, the [leading community tool](https://github.com/nektos/act/issues/74) for this has fixed [an important issue](https://github.com/nektos/act/issues/74) recently that makes it worth trying out.

I agree, I don't understand why an important framework wouldn't have a local runner, for exactly that reason.

**Comment by zbraniecki** [comment] 2020-10-13 19:00
I got a repro! Manually followed https://github.com/mozilla/grcov#usage until `cargo +nightly test` reproduced it.

I'm going to try to fix it or switch us to tarpaulin.

**Comment by zbraniecki** [comment] 2020-10-13 19:14
Ok, so the issue is described by Alex in https://github.com/rust-lang/cargo/issues/5423

I have two ideas how to fix it:
* Try to run coverage without panic=abort. Not pretty but if it gives us a reasonable coverage, we'll ride it for now and I'll report an issue to grcov.
* Switch to tarpaulin. I have an old PR https://github.com/unicode-org/icu4x/pull/184 and I verified that it doesn't require panic=abort.

**Comment by zbraniecki** [comment] 2020-10-13 20:16
fixed

**Closed by zbraniecki** 2020-10-13 20:16 UTC
Labels: C-test-infra

**Comment by zbraniecki** [comment] 2020-10-13 20:18
Reported upstream as https://github.com/mozilla/grcov/issues/494
