### ISSUE TITLE
Add Fractional Seconds to the components bag

### ISSUE THREAD

**Issue by gregtatum** [unicode-org/icu4x#1360] opened 2021-12-06 17:59 UTC
Depends on #485.

Fractional seconds should be added to the DateTimeFormat component in order to be compatible with ECMA-402's components bag.

**Comment by sffc** [comment] 2022-04-01 18:29
Possible duplicate of #485

**Comment by dminor** [comment] 2022-04-29 20:54
This is to add it to the ECMA-402 components bag. #485 didn't handle that.

**Closed** 2022-05-19 14:12 UTC
Labels: T-core, C-datetime, S-medium
