### ISSUE TITLE
How to use `yoke` to build an owning 'streaming iterator'?

### ISSUE THREAD

**Issue by Qqwy** [unicode-org/icu4x#2996] opened 2023-01-17 12:26 UTC
Fist off, let me apologise for what has become a very long wall of text 😅 .
My issue is about using Yoke for zero-copy iteration over a tree.
It is very difficult to present a minimal example for this that is not by itself already rather long. I tried my best 🙇 .

---

I am building a persistent BTreeSet where individual nodes are read from disk or network. This is done through a cache to make sure recently-used nodes do not need to be fetched again. This node-lookup method thus returns values of the type `Arc<Node<T>>`. I.e. it has the type `fn lookup(node_ref: NodeRef) -> Arc<Node<T>>`.

Simplified for example purposes, a node looks like this:

```rust
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct NodeRef(usize);

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub enum Node<T> {
  Leaf{data: Vec<T>},
  Internal{keys: Vec<T>, children: Vec<NodeRef>},
}
```

The problem is iterating a tree of these nodes. 
Because a parent node of the tree does not _actually_ own its children --they need to be looked up during iteration--, a (zero-copy) implementation of `Iterator` is impossible. 
<sub>(The only way to make this work is to store all looked-up children in an arena; which means all visited nodes are kept around until iteration has completely finished. That is of course very undesireable).</sub>

Implementing `StreamingIterator` (from the [streaming_iterator](https://docs.rs/streaming-iterator/0.1.9/streaming_iterator/) crate) _is_ possible. Here, the iterator itself owns the data it is iterating over, and it gives out a reference to its item type. Asking for the next item is only possible after relinquishing the borrow of the previous item.

Implementation of StreamingIterator to iterate over data your new iterator owns itself internally, means you're building a self-referential struct: The iterator stored in one struct field is borrowing from to the data source stored in another struct field.

And this is where Yoke comes in.

I was able to 'roll my own' that looks like this:
<sub>This implementation was in big part inspired by the excellent blog post ['Self-referential types for fun and profit'](https://morestina.net/blog/1868/self-referential-types-for-fun-and-profit)</sub>

```rust
use stable_deref_trait::StableDeref;

struct OwningStreamingIter<T, Source, Iter, StableSourceContainer>
where
    T: 'static,
    Iter: StreamingIterator<Item = &'static T>,
    StableSourceContainer: StableDeref<Target = Source>,
{
    // Actually has lifetime of '_source'
    // declared first so it is dropped first
    iter: Iter,
    _source: StableSourceContainer,
}

impl<T, Source, Iter> OwningStreamingIter<T, Source, Iter, Arc<Source>>
where
    T: 'static,
    Source: 'static,
    Iter: StreamingIterator<Item = &'static T>,
{
    fn new(source: Arc<Source>, iter_creation_fn: impl FnOnce(&'static Source) -> Iter) -> Self {
        let iter = {
            // SAFETY: Pretend like 'source' is static for a little while.
            // This is correct, as from the viewpoint of 'iter' it will behave identically:
            // - As long as 'source' is around, any references into it will remain valid as its memory location is fixed (courtesy of StableDeref).
            // - 'source' will be around for longer than 'iter': it is dropped later because of struct field ordering.
            let static_source_ref: &'static Source =
                unsafe { std::mem::transmute::<&'_ Source, &'static Source>(&*source) };
            iter_creation_fn(static_source_ref)
        };
        OwningStreamingIter {
            iter,
            _source: source,
        }
    }
}
```

Complicating things further, when iterating over a tree, you need to return a trait object (a `Box<dyn StreamingIterator<Item = T>>`) from the recursive function, because otherwise the size of the return type will not match between recursive calls.
This makes the final iterator-building function look like this:

```rust
/// Helper type because 'Box<dyn StreamingIterator>'
/// does not itself implement StreamingIterator.
struct BoxedSI<'a, K>(Box<dyn StreamingIterator<Item = K> + 'storage>);
impl<'a, K> StreamingIterator for BoxedSI<'a, K> {
    type Item = K;
    fn get(&self) -> Option<&Self::Item> {
        self.0.get()
    }
    fn advance(&mut self) {
        self.0.advance()
    }
}

pub fn tree_iter<'storage, T>(
    node: Arc<Node<T>>,
    storage: &'storage Storage<'storage>,
) -> impl StreamingIterator<Item = T> + 'storage
where
    T: Default + 'static,
{
    if node.is_leaf() {
        // Build a simple iterator over the leaves
        let iter =
            OwningStreamingIter::new(node, |node| match node {
                Node::Leaf { data, .. } => streaming_iterator::convert(data.iter()),
                _ => panic!(),
            });
        BoxedSI(Box::new(iter))
    } else {
        // Build iterator over the children:
        let iter =
            OwningStreamingIter::new(node, |node| match node {
                Node::Internal { children, .. } => streaming_iterator::convert(children.iter()),
                _ => panic!(),
            });

        // Recurse over the children:
        let iter = iter.flat_map(|child_ref| {
            let child = child_ref.lookup(storage);
            let res = tree_keys_iter2(child, storage);
            res
        });
        BoxedSI(Box::new(iter))
    }
}
```

---

While this works, I would love to use a crate that handles the 'scary bits' instead. The more I read about self-referential structs in Rust, the more I find out how easy it is to accidentally build something unsound.

This is why I'd like to use Yoke instead. At first glance, it seems exactly the right tool for the job.
However, partway through building a recursive streaming iterator I get stuck.

```rust

#[derive(Yokeable)]
/// Wrapper type to make a boxed StreamingIterator Yokeable
struct BoxedYokeableSI<'a, T: 'a>(Box<dyn StreamingIterator<Item = T> + 'a>);
impl<T> StreamingIterator for BoxedYokeableSI<'_, T> {
    type Item = T;
    fn get(&self) -> Option<&Self::Item> {
        self.0.get()
    }

    fn advance(&mut self) {
        self.0.advance()
    }
}

pub fn yoke_tree_iter<'storage, T>(
    node: Arc<Node<T>>,
    storage: &'storage StorageWrapper<'storage>,
) -> Yoke<BoxedYokeableSI<'static, T>, Arc<Node<T>>>
where
    T: Default + 'static,
{
    if node.is_leaf() {
        // Build a simple iterator over the leaves
        let yoke_iter =
            Yoke::attach_to_cart(node_arc, |node| match node {
                Node::Leaf{data, ..} => BoxedYokeableSI(Box::from(Iter(streaming_iterator::convert(data.iter())))),
                _ => unreachable!()
            });
    } else {
        // Build iterator over the children:
        let yoke_iter =
            Yoke::attach_to_cart(node_arc, |node| match node {
                Node::Internal{children, ..} => BoxedYokeableSI(Box::from(Iter(streaming_iterator::convert(children.iter())))),
                _ => unreachable!()
            });
        // Recurse over the children:
        let yoke_iter = yoke_iter.map_project(|iter, _| {
            let flat_iter = iter.flat_map(|child_ref| {
                let child = child_ref.lookup(storage);
                let res = tree_keys_iter3(child, storage);
                res
            });
            BoxedYokeableSI(Box::from(flat_iter)) // ???
        });
        yoke_iter
    }
}
```

The compiler complains about the line indicated with `// ???`:
```
the trait bound `Yoke<BoxedYokeableSI<'_, T>, std::sync::Arc<Node<T>>>: StreamingIterator` is not satisfied
```

And here I am stuck. 
I have tried to write a wrapper struct around`Yoke<BoxedYokeableSI, C>` that implements StreamingIterator. But then this struct also needs to be Yokeable, so it seems like a no-go.

What to do here? Am I missing something, or is there some functionality that needs to be added to `Yoke` to make this possible?

I'd love to contribute with a PR, though while I am reasonably fluent in 'normal' Rust, I don't fully grasp how Yoke's internals work 😅 .

Thank you very much for your time!

**Comment by Manishearth** [comment] 2023-01-19 21:18
```rust
    fn new(source: Arc<Source>, iter_creation_fn: impl FnOnce(&'static Source) -> Iter) -> Self {
```

fwiw this is extremely unsound since the function can stash the source elsewhere. Yoke's API is very very carefully designed to use HRTBs so that that's not possible.

> I have tried to write a wrapper struct around`Yoke<BoxedYokeableSI, C>` that implements StreamingIterator. But then this struct also needs to be Yokeable, so it seems like a no-go.



> I have tried to write a wrapper struct around `Yoke<BoxedYokeableSI, C>` that implements StreamingIterator. But then this struct also needs to be Yokeable, so it seems like a no-go.

Yeah this is precisely what you would have to do here. It's not clear to me why you need to nest Yokes here, but also it shouldn't be hard to implement Yokeable on a wrapper like that.

-----

Overall I think your problem here is more in your proposed solution for your problem, rather than the usage of Yoke. I don't have enough information to really understand what the problem is you are trying to solve. As far as I can tell, the nested self-referential design is not necessary here, but I could be wrong.

(As far as I can tell, a lazy-loaded streaming iterator should be possible without any self-ref stuff anyway)


(closing since this is not an actual issue, feel free to keep asking questions though I may not have time to really drill deeper. In the future, the Discussions tab is preferred for help questions.)

**Closed** 2023-02-11 15:05 UTC
