### ISSUE TITLE
Consider using 24-bit elements for inversion lists

### ISSUE THREAD

**Issue by hsivonen** [unicode-org/icu4x#4669] opened 2024-03-08 11:56 UTC
Unicode scalar values fit in 21 bits, so using 32-bit elements for inversion lists is an artifact of alignment. Since we're already doing unaligned, we should experiment with using 24-bit elements (experiment in the sense of measuring performance). If the backing array had an extra byte at the end, we could still use 32-bit unaligned loads without reading out of bounds and mask off the highest 8 bits.

**Comment by sffc** [comment] 2024-07-24 16:15
Closing as duplicate of #2807

**Closed by sffc** 2024-07-24 16:15 UTC
Labels: C-unicode
